# Generated by Django 2.2.6 on 2021-04-20 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='p_library.Publisher'),
        ),
    ]
