# Generated by Django 2.2.6 on 2021-05-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_auto_20210430_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='test',
        ),
    ]
