# Generated by Django 2.2.6 on 2021-05-12 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0009_remove_author_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateField()),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='p_library.Book')),
                ('friend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='p_library.Friend')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_holder',
            field=models.ManyToManyField(through='p_library.BorrowedBooks', to='p_library.Friend'),
        ),
    ]
