# Generated by Django 2.2.6 on 2021-05-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0013_publisher_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='address',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='city',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='country',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='state_province',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='website',
        ),
    ]
