# Generated by Django 2.2.6 on 2021-05-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0014_auto_20210520_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='books_pic/%Y/%m/%d'),
        ),
    ]
